// Generated by gencpp from file Frank_control/GetHandAnglesRequest.msg
// DO NOT EDIT!


#ifndef FRANK_CONTROL_MESSAGE_GETHANDANGLESREQUEST_H
#define FRANK_CONTROL_MESSAGE_GETHANDANGLESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Frank_control
{
template <class ContainerAllocator>
struct GetHandAnglesRequest_
{
  typedef GetHandAnglesRequest_<ContainerAllocator> Type;

  GetHandAnglesRequest_()
    {
    }
  GetHandAnglesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetHandAnglesRequest_

typedef ::Frank_control::GetHandAnglesRequest_<std::allocator<void> > GetHandAnglesRequest;

typedef boost::shared_ptr< ::Frank_control::GetHandAnglesRequest > GetHandAnglesRequestPtr;
typedef boost::shared_ptr< ::Frank_control::GetHandAnglesRequest const> GetHandAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace Frank_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::Frank_control::GetHandAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Frank_control/GetHandAnglesRequest";
  }

  static const char* value(const ::Frank_control::GetHandAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::Frank_control::GetHandAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHandAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Frank_control::GetHandAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::Frank_control::GetHandAnglesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FRANK_CONTROL_MESSAGE_GETHANDANGLESREQUEST_H
