// Generated by gencpp from file Frank_control/GetHandAngles.msg
// DO NOT EDIT!


#ifndef FRANK_CONTROL_MESSAGE_GETHANDANGLES_H
#define FRANK_CONTROL_MESSAGE_GETHANDANGLES_H

#include <ros/service_traits.h>


#include <Frank_control/GetHandAnglesRequest.h>
#include <Frank_control/GetHandAnglesResponse.h>


namespace Frank_control
{

struct GetHandAngles
{

typedef GetHandAnglesRequest Request;
typedef GetHandAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHandAngles
} // namespace Frank_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Frank_control::GetHandAngles > {
  static const char* value()
  {
    return "ae6e268c4bfe9632c21995915fa1b5ce";
  }

  static const char* value(const ::Frank_control::GetHandAngles&) { return value(); }
};

template<>
struct DataType< ::Frank_control::GetHandAngles > {
  static const char* value()
  {
    return "Frank_control/GetHandAngles";
  }

  static const char* value(const ::Frank_control::GetHandAngles&) { return value(); }
};


// service_traits::MD5Sum< ::Frank_control::GetHandAnglesRequest> should match
// service_traits::MD5Sum< ::Frank_control::GetHandAngles >
template<>
struct MD5Sum< ::Frank_control::GetHandAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Frank_control::GetHandAngles >::value();
  }
  static const char* value(const ::Frank_control::GetHandAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Frank_control::GetHandAnglesRequest> should match
// service_traits::DataType< ::Frank_control::GetHandAngles >
template<>
struct DataType< ::Frank_control::GetHandAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::Frank_control::GetHandAngles >::value();
  }
  static const char* value(const ::Frank_control::GetHandAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Frank_control::GetHandAnglesResponse> should match
// service_traits::MD5Sum< ::Frank_control::GetHandAngles >
template<>
struct MD5Sum< ::Frank_control::GetHandAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Frank_control::GetHandAngles >::value();
  }
  static const char* value(const ::Frank_control::GetHandAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Frank_control::GetHandAnglesResponse> should match
// service_traits::DataType< ::Frank_control::GetHandAngles >
template<>
struct DataType< ::Frank_control::GetHandAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::Frank_control::GetHandAngles >::value();
  }
  static const char* value(const ::Frank_control::GetHandAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANK_CONTROL_MESSAGE_GETHANDANGLES_H
