# OHand 机械手连接设置
ohand_left_settings:
  serial_port: '/dev/ttyUSB0'  # 左手 OHand 连接的串口号 (示例)
  slave_id: 2                 # 左手 OHand 的 Modbus 从站 ID (示例)
  enabled: true               # 是否启用左手控制

ohand_right_settings:
  serial_port: '/dev/ttyUSB1' # 右手 OHand 连接的串口号 (示例)
  slave_id: 2                 # 右手 OHand 的 Modbus 从站 ID (示例)
  enabled: true               # 是否启用右手控制

# 共享的视觉角度到 OHand 角度的映射参数
# 这些是 compute_finger_angles_from_visual 函数输出的视觉角度范围 (经过插值和限制后)
# 也是 translate_angle 函数的视觉输入范围
shared_visual_input_mapping:
  thumb_bend_input_min: 90
  thumb_bend_input_max: 165
  other_fingers_bend_input_min: 0
  other_fingers_bend_input_max: 165
  thumb_rot_input_min: 75   # 拇指旋转的视觉输入范围，根据实际情况校准
  thumb_rot_input_max: 0
# --- Visual Input Mapping for Left Hand ---
# These define the expected range of 'processed' visual angles from get_hand_visual_angles
# which then serve as the input range for the translate_angle function for the Left hand.
left_visual_input_mapping:
  thumb_bend_input_min: 90    # Example for left hand
  thumb_bend_input_max: 165   # Example for left hand
  other_fingers_bend_input_min: 0
  other_fingers_bend_input_max: 160 # Example for left hand
  thumb_rot_input_min: 0    # Example for left hand (raw visual rotation input range)
  thumb_rot_input_max: 75     # Example for left hand

# --- Visual Input Mapping for Right Hand ---
right_visual_input_mapping:
  thumb_bend_input_min: 85    # Example for right hand (can be different)
  thumb_bend_input_max: 170   # Example for right hand
  other_fingers_bend_input_min: 5
  other_fingers_bend_input_max: 165 # Example for right hand
  thumb_rot_input_min: 75      # Example for right hand, user example: max (0) < min (75)
  thumb_rot_input_max: 0     # This means a rotation from 0 to 75 maps to ohand range.
                                # If raw visual is 0, it's at min_rot. If raw is 75, it's at max_rot.
                                # Original user example: min:75, max:0. If this is intended,
                                # the translate_angle function will invert the mapping.
                                # For clarity, typically min < max. Let's use min:0, max:75 for this example.
                                # If you truly need min > max, the code should handle it.

# 左手 OHand 的目标角度范围
left_ohand_output_mapping:
  thumb_bend_range: [0, 45]
  finger_bend_range: [0, 180]
  thumb_rot_range: [-45, 135]

# 右手 OHand 的目标角度范围
right_ohand_output_mapping:
  thumb_bend_range: [0, 45]   # 示例：右手范围可能略有不同
  finger_bend_range: [0, 180]
  thumb_rot_range: [22, 0]

# MediaPipe Hands 检测设置
mediapipe_hands_settings:
  min_detection_confidence: 0.7 # 稍微降低以便更容易检测到双手
  min_tracking_confidence: 0.6
  max_num_hands: 2              # 关键：设置为2以检测两只手

# Orbbec 摄像头设置
orbbec_camera_settings:
  serial_number: '' # 留空则自动检测第一个

# 通用设置
general_settings:
  send_interval_seconds: 0.05 # 发送指令到 OHand 的时间间隔（秒）